#!/bin/bash

# Update package repositories
sudo apt update 

# Install OpenJDK 17 Runtime Environment
sudo apt install openjdk-17-jre -y 

# Download Jenkins GPG key and add it to APT keyring
sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian/jenkins.io-2023.key

# Add Jenkins repository to APT sources
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null

# Update package repositories to include Jenkins repository
sudo apt-get update

# Install Jenkins package
sudo apt-get install jenkins -y 

# Install Git
sudo apt install git -y 

# Install Apache Maven
sudo apt install maven -y

# Check the status of Jenkins service
sudo systemctl status jenkins
