version: "3.8"

services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/configdb/mongo-keyfile"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo1_data:/data/db
      - /home/ubuntu/mongo-keyfile:/data/configdb/mongo-keyfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    restart: always
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/configdb/mongo-keyfile"]
    volumes:
      - mongo2_data:/data/db
      - /home/ubuntu/mongo-keyfile:/data/configdb/mongo-keyfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    restart: always
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/configdb/mongo-keyfile"]
    volumes:
      - mongo3_data:/data/db
      - /home/ubuntu/mongo-keyfile:/data/configdb/mongo-keyfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
